language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script: 
 - echo 'date.timezone = "UTC"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - composer install -o -n
 - vendor/bin/phpunit --version
 - mkdir -p build/logs

script: 
 - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v
